routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Auth::routes();

Route::group(['namespace' => 'Manage', 'middleware' => 'auth', 'prefix' => 'manage'], function () {
	Route::resource('staff', 'StaffController');

	Route::get('staff/{staff}/courses', 'Staff\CourseController@index')->name('manage.staff.courses.index');
	Route::get('staff/{staff}/courses/create', 'Staff\CourseController@create')->name('manage.staff.courses.create');
	Route::get('staff/{staff}/courses/{course}', 'Staff\CourseController@show')->name('manage.staff.courses.show');
	Route::post('staff/{staff}/courses', 'Staff\CourseController@store')->name('manage.staff.courses.store');

	Route::resource('colleges', 'CollegeController');
});

Route::group(['namespace' => 'Settings', 'middleware' => 'auth'], function () {
	Route::get('settings/change-academic-year', 'AcademicYearController@edit')->name('change-academic-year.edit');
	Route::post('settings/change-academic-year', 'AcademicYearController@update')->name('change-academic-year.update');
});

Route::group(['prefix' => 'staff-area', 'namespace' => 'Staff', 'middleware' => 'auth'], function () {
	Route::get('courses', 'CourseController@index')->name('staff.courses.index');
	Route::get('courses/{course}', 'CourseController@show')->name('staff.courses.show');
	
	Route::resource('courses.teaching-plans', 'TeachingPlanController');

	Route::get('students', 'StudentController@index')->name('staff.students.index');
	Route::get('students/{student}', 'StudentController@show')->name('staff.students.show');
});

// Library
Route::group(['prefix' => 'library', 'namespace' => 'Library', 'middleware' => 'auth'], function () {
	Route::get('student-attendances', 'StudentAttendaceController@index')->name('library.student-attendances.index');
	Route::post('student-attendances', 'StudentAttendaceController@store')->name('library.student-attendances.store');
});

app/Models/AcademicYear.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class AcademicYear extends Model
{
    //
}

app/Models/College.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class College extends Model
{
    //
}

app/Models/Course.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Course extends Model
{
    public function teachingPlans()
    {
        return $this->hasMany(TeachingPlan::class);
    }

    public function classAttendances()
    {
        return $this->hasMany(StaffClassAttendance::class);
    }
}

app/Models/CourseAssesment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class CourseAssesment extends Model
{
    //
}

app/Models/Department.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Department extends Model
{
    //
}

app/Models/Detail.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Detail extends Model
{
    //
}

app/Models/Laboratory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Laboratory extends Model
{
    //
}

app/Models/Library.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Library extends Model
{
    public function students()
    {
    	return $this->belongsToMany(Student::class, 'student_library_attendances');
    }
}

app/Models/Permission.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Permission extends Model
{
    //
}

app/Models/Program.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Program extends Model
{
    //
}

app/Models/ProgramType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ProgramType extends Model
{
    //
}

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    //
}

app/Models/School.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class School extends Model
{
    //
}

app/Models/Semester.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Semester extends Model
{
    //
}

app/Models/Staff.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Session;

class Staff extends Model
{

    public function name()
    {
        return $this->title . ' ' . $this->first_name . ' ' . $this->middle_name . ' ' . $this->last_name;
    }
    
    public function courses()
    {
        return $this->belongsToMany(Course::class)
            ->withTimestamps()
            ->withPivot(['academic_year_id', 'semester_id']);
    }

    public function coursesCount()
    {
        return $this->courses()->whereAcademicYearId(Session::get('academicYear')->id)->count();
    }

    public function getCoursesInActiveAcademicYear()
    {
        return $this->courses()->where('academic_year_id', Session::get('academicYear')->id);
    }

    public function students()
    {
        return $this->belongsToMany(Student::class, 'academic_advisors')
            ->withTimestamps()
            ->withPivot(['academic_year_id', 'semester_id']);
    }

    public function libraries()
    {
        return $this->belongsToMany(Library::class);
    }
}

app/Models/StaffClassAttendance.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class StaffClassAttendance extends Model
{
    //
}

app/Models/Student.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    public function name()
    {
        return $this->first_name . ' ' . $this->middle_name . ' ' . $this->last_name;
    }

    public function consultationSessions()
    {
        return $this->hasMany(StudentAcademicAdvisorsConsultation::class);
    }
}

app/Models/TeachingPlan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class TeachingPlan extends Model
{
    public function courseAssesment()
    {
        return $this->belongsTo(CourseAssesment::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'username', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function staff()
    {
        return $this->hasOne(Staff::class);
    }

    public function isStaff()
    {
        if (!$this->staff)
        {
            return false;
        }

        return true;
    }
}

app/Models/Venue.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Venue extends Model
{
    //
}

resources/views/home.blade.php
@extends('layouts.primary')

@section('page_title', 'Welcome')

@section('main')

<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">Home</h3>
	</div>
	<div class="panel-body">
		...
	</div>
</div>

@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@yield('title') | {{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        
        @include('layouts.partials._navbar')
        
        @include('layouts.partials._flash_message')

        @yield('content')

        @include('layouts.partials._footer')

    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/layouts/partials/_flash_message.blade.php
@if (notify()->ready())
    <div class="alert alert-{{ notify()->type() }}">
        {{ notify()->message() }}
    </div>
@endif

resources/views/layouts/partials/_footer.blade.php
<footer>
	<div class="container">
		<p class="text-center">Copyright &copy; {{ date('Y') }} | {{ config('app.name') }}</p>
	</div>
</footer>

resources/views/layouts/partials/_navbar.blade.php
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">

            <!-- Collapsed Hamburger -->
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- Branding Image -->
            <a class="navbar-brand" href="{{ url('/') }}">
                {{ config('app.name', 'Laravel') }}
            </a>
        </div>

        <div class="collapse navbar-collapse" id="app-navbar-collapse">
            <!-- Left Side Of Navbar -->
            <ul class="nav navbar-nav">
                &nbsp;
            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="nav navbar-nav navbar-right">
                <!-- Authentication Links -->
                @if (Auth::guest())
                    &nbsp;
                @else
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            {{ Auth::user()->username }} <span class="caret"></span>
                        </a>

                        <ul class="dropdown-menu" role="menu">
                            <li><a href="#">My Profile</a></li>
                            <li><a href="#">Change Password</a></li>
                            <li>
                                <a href="{{ route('logout') }}"
                                    onclick="event.preventDefault();
                                             document.getElementById('logout-form').submit();">
                                    Logout
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    {{ csrf_field() }}
                                </form>
                            </li>
                        </ul>
                    </li>
                @endif
            </ul>
        </div>
    </div>
</nav>

resources/views/layouts/partials/_sidebar.blade.php
<!-- All -->
All
<div class="list-group">
    <a href="{{ route('home') }}" class="list-group-item active">Home</a>
    <a href="#" class="list-group-item">Item 3</a>
    <a href="{{ route('change-academic-year.edit') }}" class="list-group-item">Change Academic Year</a>
</div>
<!-- // All -->

<!-- Principal of college -->
Principal of college
<div class="list-group">
	<a href="#" class="list-group-item">Item 2</a>
	<a href="#" class="list-group-item">Item 3</a>
</div>
<!-- // Principal of college -->

<!-- Dean of school -->
Dean of school
<div class="list-group">
	<a href="#" class="list-group-item">Item 2</a>
	<a href="#" class="list-group-item">Item 3</a>
</div>
<!-- // Dean of school -->

<!-- Head of Department -->
Head of department
<div class="list-group">
    <a href="{{ route('staff.index') }}" class="list-group-item">Staff</a>
	<a href="#" class="list-group-item">Item 3</a>
</div>
<!-- // Head of Department -->

<!-- Staff -->
Staff
<div class="list-group">
	<a href="{{ route('staff.courses.index') }}" class="list-group-item">Courses</a>
	<a href="{{ route('staff.students.index') }}" class="list-group-item">Students</a>
	<a href="#" class="list-group-item">Item 3</a>
</div>
<!-- // Staff -->

<!-- Library -->
Library
<div class="list-group">
	<a href="{{ route('library.student-attendances.index') }}" class="list-group-item">Student Attendance</a>
	<a href="#" class="list-group-item">Item 2</a>
	<a href="#" class="list-group-item">Item 3</a>
</div>
<!-- // Library -->

<!-- Class representative -->
Class representative
<div class="list-group">
	<a href="#" class="list-group-item">Item 2</a>
	<a href="#" class="list-group-item">Item 3</a>
</div>
<!-- // Class representative -->

<!-- Student -->
Student
<div class="list-group">
	<a href="#" class="list-group-item">Item 2</a>
	<a href="#" class="list-group-item">Item 3</a>
</div>
<!-- // Student -->

<!-- Manage -->
Manage
<div class="list-group">
	<a href="{{ route('colleges.index') }}" class="list-group-item">Colleges</a>
	<a href="#" class="list-group-item">Item 3</a>
</div>
<!-- // Manage -->

resources/views/layouts/partials/_topbar.blade.php
@if(Auth::check())
<div class="panel panel-default">
    <div class="panel-body">
        <div class="row">
            <div class="col-sm-4">
                <strong>Logged in as:</strong> {{ Auth::user()->username }}
            </div>
            <div class="col-sm-4 hidden-xs">
                <strong>Academic Year: </strong> {{ Session::get('academicYear')->name }}
            </div>
            <div class="col-sm-4 hidden-xs">
                {{ Carbon\Carbon::now()->format('l jS \\of F Y') }}
            </div>
        </div>
    </div>
</div>
@endif

resources/views/layouts/primary.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@yield('page_title') | {{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
       
        @include('layouts.partials._navbar')
        
        @include('layouts.partials._flash_message')


            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <!-- Top bar -->
                        @include('layouts.partials._topbar')
                        <!-- // Top bar -->        
                    </div>        
                </div>
                <div class="row">
                    <div class="col-md-2">
                        @include('layouts.partials._sidebar')
                    </div>
                    <div class="col-md-10">

                        @yield('main')

                    </div>
                </div>
            </div>        

        @include('layouts.partials._footer')
        
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/layouts/secondary.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@yield('page_title') | {{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
       
        @include('layouts.partials._navbar')
        
        @include('layouts.partials._flash_message')


            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <!-- Top bar -->
                        @include('layouts.partials._topbar')
                        <!-- // Top bar -->        
                    </div>        
                </div>
                <div class="row">
                    <div class="col-md-2">
                        @include('layouts.partials._sidebar')
                    </div>
                    <div class="col-md-7">

                        @yield('main')

                    </div>
                    <div class="col-md-3">

                        @yield('aside')

                    </div>
                </div>
            </div>        

        @include('layouts.partials._footer')
        
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>